OUTPUT:
b'\r\n(WERI_cwatm) D:\\Mehdi\\monthly\\CWatM\\Toolkit\\Calibration\\runs_calibration\\05_002>call C:/Users/psh2610/WERI_cwatm/Scripts/activate \r\nCWATM - Community Water Model  1.5  Date:  21.12.2024  \r\nInternational Institute of Applied Systems Analysis (IIASA)\r\nRunning under platform:  Windows\r\n-----------------------------------------------------------\r\n'
ERRORS:
b'Traceback (most recent call last):\r\n  File "D:\\Mehdi\\monthly\\CWatM\\run_cwatm.py", line 39, in <module>\r\n    main(settings, args)\r\n    ~~~~^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 338, in main\r\n    success, last_dis = CWATMexe(settingsfile[0])\r\n                        ~~~~~~~~^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 133, in CWATMexe\r\n    CWATM = CWATModel()\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\cwatm_initial.py", line 166, in __init__\r\n    self.routing_kinematic_module.initial()\r\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\hydrological_modules\\routing_reservoirs\\routing_kinematic.py", line 210, in initial\r\n    report(self.var.catchment,file)\r\n    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\management_modules\\data_handling.py", line 1937, in report\r\n    ds = gdal.GetDriverByName(\'GTiff\').Create(name, nx, ny, 1, gdal.GDT_Float32, [\'COMPRESS=LZW\'])\r\n  File "C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal.py", line 3836, in Create\r\n    return _gdal.Driver_Create(self, *args, **kwargs)\r\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\r\nRuntimeError: Deleting D:\\Mehdi\\Files\\out_cwatm_30min_khozestan_26Apr\\basin.tif failed:\r\nPermission denied\r\n'