OUTPUT:
b'\r\n(WERI_cwatm) D:\\Mehdi\\monthly\\CWatM\\Toolkit\\Calibration\\runs_calibration2\\02_003>call C:/Users/psh2610/WERI_cwatm/Scripts/activate \r\nCWATM - Community Water Model  1.5  Date:  21.12.2024  \r\nInternational Institute of Applied Systems Analysis (IIASA)\r\nRunning under platform:  Windows\r\n-----------------------------------------------------------\r\n'
ERRORS:
b'Traceback (most recent call last):\r\n  File "D:\\Mehdi\\monthly\\CWatM\\run_cwatm.py", line 39, in <module>\r\n    main(settings, args)\r\n    ~~~~^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 338, in main\r\n    success, last_dis = CWATMexe(settingsfile[0])\r\n                        ~~~~~~~~^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\run_cwatm.py", line 133, in CWATMexe\r\n    CWATM = CWATModel()\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\cwatm_initial.py", line 166, in __init__\r\n    self.routing_kinematic_module.initial()\r\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\hydrological_modules\\routing_reservoirs\\routing_kinematic.py", line 210, in initial\r\n    report(self.var.catchment,file)\r\n    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "D:\\Mehdi\\monthly\\CWatM\\cwatm\\management_modules\\data_handling.py", line 1949, in report\r\n    outband.WriteArray(value)\r\n    ~~~~~~~~~~~~~~~~~~^^^^^^^\r\n  File "C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal.py", line 8344, in WriteArray\r\n    return gdal_array.BandWriteArray(self, array, xoff, yoff,\r\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\r\n                                      resample_alg=resample_alg,\r\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n                                      callback=callback,\r\n                                      ^^^^^^^^^^^^^^^^^^\r\n                                      callback_data=callback_data)\r\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal_array.py", line 675, in BandWriteArray\r\n    ret = BandRasterIONumPy(band, 1, xoff, yoff, xsize, ysize,\r\n                             array, datatype, resample_alg, callback, callback_data)\r\n  File "C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal_array.py", line 256, in BandRasterIONumPy\r\n    return _gdal_array.BandRasterIONumPy(band, bWrite, xoff, yoff, xsize, ysize, psArray, buf_type, resample_alg, callback, callback_data)\r\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\nRuntimeError: basin.tif: Bogus block size; unable to allocate a buffer.\r\nMay be caused by: TIFFScanlineSize64:Computed scanline size is zero\r\nMay be caused by: TIFFWriteDirectorySec:Starting directory 0 at offset 0x0 (0) might cause an IFD loop\r\nException ignored in: <built-in function delete_Dataset>\r\nRuntimeError: basin.tif: FillEmptyTiles() failed because panByteCounts == NULL\r\n'